export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_FEED = 'FETCH_FEED';
